In [293]:
""" Kinematic chain of a robot arm (planar)
    Assignment 
"""

' Kinematic chain of a robot arm (planar)\n    Assignment \n'


![](https://github.com/eraldoribeiro/assignment_robotarm2D/blob/main/robotArm01.png?raw=1)
*Figure 1*: A two-dimensional articulated arm. The articulated structure has 3 local coordinate frames each one centered at a joint. For each part, the local x-axis is aligned with the part.  

Consider the arm structure shown in Figure 1. Assume the following values for the arm configuration: 
- The location of the first joint (i.e., the one that is attached to the ground support) is ${\bf p}_1 = \left(3,2\right)^\mathsf{T}$. 
- The lengths of the parts are $L_1 = 5$ and  $L_2 = 8$.

In [294]:
import numpy as np
import math as mph

### Question 1

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [295]:
# Answer goes here. Add more code/markdown cells as needed
phi1 = np.pi/4

p_1 = np.array([[3], [2]])

T_01 = np.array([[np.cos(phi1), -np.sin(phi1), p_1[0][0]],
                 [np.sin(phi1),  np.cos(phi1), p_1[1][0]],
                 [           0,             0, 1]])

print("transformation matrix from frame 1 to 0 is \n", T_01)



transformation matrix from frame 1 to 0 is 
 [[ 0.70710678 -0.70710678  3.        ]
 [ 0.70710678  0.70710678  2.        ]
 [ 0.          0.          1.        ]]


In [296]:
L1 = 5
L2 = 8

phi2 = np.pi/8

T_12 = np.array([[np.cos(phi2), -np.sin(phi2), L1], 
                 [np.sin(phi2),  np.cos(phi2),  0],
                 [           0,             0,  1]])
                
print("transformation matrix from frame 2 to 1 is \n", T_12)

transformation matrix from frame 2 to 1 is 
 [[ 0.92387953 -0.38268343  5.        ]
 [ 0.38268343  0.92387953  0.        ]
 [ 0.          0.          1.        ]]


In [297]:
T_23 = np.array([[1, 0, L2],
                 [0, 1,  0],
                 [0, 0,  1]])

print("transformation matrix from frame 3 to 2 is \n", T_23)

transformation matrix from frame 3 to 2 is 
 [[1 0 8]
 [0 1 0]
 [0 0 1]]


### Question 2

Write the matrices that represent each local frame w.r.t. the global frame $\mathcal F\{0\}$. The transformations you need to write are $T_{0,1}$, $T_{0,2}$, and $T_{0,3}$.

In [298]:
# Answer goes here. Add more code/markdown cells as needed

# transformation matrix of frame 1 -> 0 is already known
print("transformation matrix from frame 1 to 0 is \n", T_01)



transformation matrix from frame 1 to 0 is 
 [[ 0.70710678 -0.70710678  3.        ]
 [ 0.70710678  0.70710678  2.        ]
 [ 0.          0.          1.        ]]


In [299]:
# Matrix multiplication to find transformation matrix of 2 -> 0
T_02 = T_01 @ T_12


print("transformation matrix from frame 2 to 0 is \n", T_02)

transformation matrix from frame 2 to 0 is 
 [[ 0.38268343 -0.92387953  6.53553391]
 [ 0.92387953  0.38268343  5.53553391]
 [ 0.          0.          1.        ]]


In [300]:
# Matrix multiplication to find transformation matrix of 3 -> 0
T_03 = T_01 @ T_12 @ T_23

print("transformation matrix from frame 3 to 0 is \n", T_03)

transformation matrix from frame 3 to 0 is 
 [[ 0.38268343 -0.92387953  9.59700136]
 [ 0.92387953  0.38268343 12.92657017]
 [ 0.          0.          1.        ]]


### Question 3

Write the matrices that represent the local coordinate frames $\mathcal F\{1\}$, $\mathcal F\{2\}$, and $\mathcal F\{3\}$. These frames are indicated in green in Figure 1. The transformation matrices you need to write are $T_{0,1}$, $T_{1,2}$, and $T_{2,3}$.

In [301]:
# Answer goes here. Add more code/markdown cells as needed

# Students were told to ignore question 3 #



### Question 4

Using the transformations from the previous questions, calculate the global coordinates of the middle point of each part of the robot arm when $\phi_1 = \pi/8$ and $\phi_2 = \pi/4$. Hint: the location of the middle point of part 1 is $(\frac{L_1}{2},0)^\mathsf{T}$ (w.r.t. frame $\mathcal F\{1\}$).

In [302]:
# Answer goes here. Add more code/markdown cells as needed

mid_locf1 = np.array([[L1/2], [0], [1]])

mid_globf1 = T_01 @ mid_locf1

print("The global coordinates of the mid point of L1 is \n", mid_globf1)



The global coordinates of the mid point of L1 is 
 [[4.76776695]
 [3.76776695]
 [1.        ]]


### Question 5

Using the transformations from the previous questions, calculate the global coordinates of all the joint points and the end-effector location when $\phi_1 = \pi/4$ and $\phi_2 = \pi/8$. 

In [303]:
# Answer goes here. Add more code/markdown cells as needed

joint_locf1 = np.array([[0], [0], [1]])
joint_globf1 = T_01 @ joint_locf1

print("The global coordinates of the first joint are\n", joint_globf1)

The global coordinates of the first joint are
 [[3.]
 [2.]
 [1.]]


In [304]:
joint_locf2 = np.array([[0], [0], [1]])
joint_globf2 = T_02 @ joint_locf2

print("The global coordinates of the second joint are\n", joint_globf2)

The global coordinates of the second joint are
 [[6.53553391]
 [5.53553391]
 [1.        ]]


In [305]:
end_locf3 = np.array([[0], [0], [1]])
end_globf3 = T_03 @ end_locf3

print("The global coordinates of the end effector are\n", end_globf3)

The global coordinates of the end effector are
 [[ 9.59700136]
 [12.92657017]
 [ 1.        ]]


### Question 6

Write the matrix that represents the coordinate frame of the end effector w.r.t. frame  $\mathcal F\{1\}$, i.e., $T_{1,3}$

In [306]:
# Answer goes here. Add more code/markdown cells as needed

T_13 = T_12 @ T_23

print("The frame of the end effector w.r.t f1 is \n", T_13)

The frame of the end effector w.r.t f1 is 
 [[ 0.92387953 -0.38268343 12.39103626]
 [ 0.38268343  0.92387953  3.06146746]
 [ 0.          0.          1.        ]]


### Question 7

Write the matrix that represents the coordinate frame $\mathcal F\{1\}$ w.r.t. to the frame of the end effector

In [307]:
# Answer goes here. Add more code/markdown cells as needed

T_31 = T_23 @ T_12

print("The frame of f1 w.r.t the end effector is \n", T_31)

The frame of f1 w.r.t the end effector is 
 [[ 0.92387953 -0.38268343 13.        ]
 [ 0.38268343  0.92387953  0.        ]
 [ 0.          0.          1.        ]]
